/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author dwij
 */


#include <bits/stdc++.h>


using namespace std;

/*******  All Required define Pre-Processors and typedef Constants *******/
#define endl '\n'

/**********************************************/




class CTwoTeamsComposing {
public:
    void solve(istream &in, ostream &out) {

        int T;
        in >> T;
        while (T--) {
            int n;
            in >> n;
            map<int, int> mp;

            for (int i = 0; i < n; ++i) {
                int k;
                in >> k;
                mp[k]++;
            }

            int mx = -1;
            for (auto n: mp) {
                mx = fmax(mx, n.second);
            }

            if (mp.size() > mx) out << mx << endl;
            else if (mp.size() == mx) out << mx - 1 << endl;
            else out << mp.size() << endl;

        }

    }
};


int main() {
    CTwoTeamsComposing solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);

    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    cout.tie(nullptr);

    solver.solve(in, out);
    return 0;
}
